# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Load Challenge Manually

on:
  schedule:
    - cron: "1 6 1-24 12 *"

on: 
  workflow_dispatch:
    inputs:
      year:
        description: 'Year'     
        required: true
        default: '2020'
      day:
        description: 'Day'     
        required: true
        default: '1'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version 1.5.3
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.5.3
      - name: Create dir with files in repo
        env:
          SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
        run: yarn loadChallenge --year ${{ steps.current-time.outputs.year }} --day ${{ steps.current-time.outputs.day }} --partTwo
      - run: |
          git config user.name NiewView
          git config user.email tom.eckardt.it@gmail.com
          git add .
          git commit -m "loaded new challenge from advent of code"
          git push
