# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Load Challenge from Advent Of Code

on:
  push:	  schedule:
    branches: [master]
  # schedule:
  #   - cron: "2 11 1-24 12 *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version 1.5.3
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.5.3
      - name: Set current year as env variable
        run: echo "::set-env name=YEAR::$('%Y')"
      - name: Set current day as env variable
        run: echo "::set-env name=DAY::$('%d')"
      - name: Crete dir with files in repo
        run: yarn loadChallenge --year $YEAR --day $DAY
      - run: |
          git config user.name NiewView
          git config user.email tom.eckardt.it@gmail.com
          git add .
          git commit -m "loaded new challenge from advent of code"
          git push
