# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Load Challenge from Advent Of Code

on:
  push:
    branches: [master]
  # schedule:
  #   - cron: "2 11 1-24 12 *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version 1.5.3
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.5.3
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
      - name: Crete dir with files in repo
        run: yarn loadChallenge --year $YEAR --day $DAY
      - run: |
          git config user.name NiewView
          git config user.email tom.eckardt.it@gmail.com
          git add .
          git commit -m "loaded new challenge from advent of code"
          git push
