# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Load Challenge Part 2 from Advent Of Code

on:
  push:
    branches:
      - master     

jobs:
  test:
    if: ${{ github.event.commits == contains(join(github.event.commits.*.message, ', '), 'part1 \#') == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version 1.5.3
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.5.3
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+01:00"
      - name: Create dir with files in repo
        env:
          SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
        run: yarn loadChallenge --year ${{ steps.current-time.outputs.year }} --day ${{ steps.current-time.outputs.day }} --partTwo
      - run: |
          git config user.name NiewView
          git config user.email tom.eckardt.it@gmail.com
          git add .
          git commit -m "loaded new challenge from advent of code"
          git push
